info:
  description: API for managing advertisements in the Online Boutique application.
  title: Ad Service
  version: 1.0.0
openapi: 3.0.3
paths:
  /ads:
    get:
      parameters:
      - description: The context for which to retrieve advertisements (e.g., product
          category).
        in: query
        name: context
        required: true
        schema:
          example: clothing
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  properties:
                    ad_id:
                      example: ad123
                      type: string
                    content:
                      example: Buy one, get one free!
                      type: string
                    image_url:
                      example: http://example.com/ad123.png
                      type: string
                    target_url:
                      example: http://example.com/shop
                      type: string
                  type: object
                type: array
          description: List of advertisements
        '400':
          content:
            application/json:
              schema:
                properties:
                  error:
                    example: Invalid context provided.
                    type: string
                type: object
          description: Invalid context parameter
        '500':
          content:
            application/json:
              schema:
                properties:
                  error:
                    example: An unexpected error occurred.
                    type: string
                type: object
          description: Internal server error
      summary: Get advertisements for a given context
servers:
- description: Ad Service in Kubernetes
  url: http://adservice.default.svc.cluster.local
