info:
  description: API for managing product details in the Online Boutique application.
  title: Product Catalog Service
  version: 1.0.0
openapi: 3.0.3
paths:
  /products:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  properties:
                    description:
                      example: A comfortable shirt.
                      type: string
                    id:
                      example: product123
                      type: string
                    image_url:
                      example: http://example.com/shirt.png
                      type: string
                    name:
                      example: Shirt
                      type: string
                    price:
                      example: 29.99
                      type: number
                  type: object
                type: array
          description: List of products
        '500':
          content:
            application/json:
              schema:
                properties:
                  error:
                    example: Unable to fetch products.
                    type: string
                type: object
          description: Error retrieving products
      summary: Retrieve all products
  /products/{id}:
    get:
      parameters:
      - description: The unique identifier of the product.
        in: path
        name: id
        required: true
        schema:
          example: product123
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  description:
                    example: A comfortable shirt.
                    type: string
                  id:
                    example: product123
                    type: string
                  image_url:
                    example: http://example.com/shirt.png
                    type: string
                  name:
                    example: Shirt
                    type: string
                  price:
                    example: 29.99
                    type: number
                type: object
          description: Product details
        '404':
          content:
            application/json:
              schema:
                properties:
                  error:
                    example: Product not found.
                    type: string
                type: object
          description: Product not found
        '500':
          content:
            application/json:
              schema:
                properties:
                  error:
                    example: Unable to fetch product details.
                    type: string
                type: object
          description: Error retrieving product details
      summary: Retrieve details for a specific product
servers:
- description: Product Catalog Service in Kubernetes
  url: http://productcatalogservice.default.svc.cluster.local
