openapi: 3.0.3
info:
  title: Recommendation Service
  description: API for suggesting products.
  version: 1.0.0
servers:
  - url: http://recommendationservice.default.svc.cluster.local
    description: Recommendation Service
paths:
  /recommendations:
    get:
      summary: Get product recommendations
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: string
            example: user123
      responses:
        200:
          description: Recommended products
          content:
            application/json:
              schema:
                type: object
                properties:
                  recommendations:
                    type: array
                    items:
                      type: object
                      properties:
                        product_id:
                          type: string
                          example: prod456
                        reason:
                          type: string
                          example: \"Frequently bought together\"
