apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  annotations:
    github.com/project-slug: GoogleCloudPlatform/microservices-demo
  description: API for managing shopping cart items.
  name: boutique-cart-api
  tags:
  - api
  - cart
  - boutique
spec:
  lifecycle: production
  owner: team-cart
  type: openapi
  definition:
    type: file
    file: ./spec/cart_openapi.yaml
