apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  annotations:
    github.com/project-slug: GoogleCloudPlatform/microservices-demo
  description: API for processing orders during checkout.
  name: boutique-checkout-api
  tags:
  - api
  - checkout
  - boutique
spec:
  lifecycle: production
  owner: team-checkout
  type: openapi
  definition: |
    openapi: 3.0.3
    info:
      title: Checkout Service
      description: API for processing orders during checkout.
      version: 1.0.0
    servers:
      - url: http://checkoutservice.default.svc.cluster.local
        description: Checkout Service
    paths:
      /checkout:
        post:
          summary: Process an order
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    user_id:
                      type: string
                      example: user123
                    items:
                      type: array
                      items:
                        type: object
                        properties:
                          product_id:
                            type: string
                            example: prod123
                          quantity:
                            type: integer
                            example: 2
          responses:
            200:
              description: Order processed successfully
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      order_id:
                        type: string
                        example: order123
