apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  annotations:
    github.com/project-slug: GoogleCloudPlatform/microservices-demo
  description: API for sending emails.
  name: boutique-email-api
  tags:
  - api
  - email
  - boutique
spec:
  lifecycle: production
  owner: team-email
  type: openapi
  definition:
    type: file
    file: ./spec/email_openapi.yaml
