apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  annotations:
    github.com/project-slug: GoogleCloudPlatform/microservices-demo
  description: API for managing shipping details.
  name: boutique-shipping-api
  tags:
  - api
  - shipping
  - boutique
spec:
  lifecycle: production
  owner: team-shipping
  type: openapi
  definition: |
    openapi: 3.0.3
    info:
      title: Shipping Service
      description: API for managing shipping details.
      version: 1.0.0
    servers:
      - url: http://shippingservice.default.svc.cluster.local
        description: Shipping Service
    paths:
      /ship:
        post:
          summary: Ship an order
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    order_id:
                      type: string
                      example: order123
                    address:
                      type: object
                      properties:
                        street:
                          type: string
                          example: 123 Main St
                        city:
                          type: string
                          example: San Francisco
                        zip:
                          type: string
                          example: 94105
          responses:
            200:
              description: Shipping details
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      tracking_number:
                        type: string
                        example: track123
