kind: Component
spec:
  type: Service
  lifecycle: prod
  owner: joseph.titra@harness.io
  system: boutique-webstore
  dependsOn: []
  providesApis: []
apiVersion: backstage.io/v1alpha1
metadata:
  name: boutique-frontend
  description: Frontend for the boutique online store
  links:
    - url: http://34.67.7.165/
      title: Prod Website
      icon: dashboard
      type: Boutique FrontEnd
    - url: http://34.28.46.65
      title: QA Website
      icon: dashboard
      type: Boutique FrontEnd
    - url: http://34.135.60.81/
      title: Dev Website
      icon: dashboard
      type: Boutique FrontEnd
  tags: 
    - go
  annotations:
    harness.io/project-url: https://app.harness.io/ng/account/V-5I-pmQSvSqLW37ZD333Q/all/orgs/default/projects/default_project
    github.com/project-slug: GoogleCloudPlatform/microservices-demo
    # For Harness CI/CD plugin
    harness.io/pipelines: |
      Build and Deploy: https://app.harness.io/ng/account/V-5I-pmQSvSqLW37ZD333Q/all/orgs/default/projects/default_project/pipelines/DevSecOps/pipeline-studio?storeType=INLINE
    harness.io/services: |
      boutique_frontend: https://app.harness.io/ng/account/V-5I-pmQSvSqLW37ZD333Q/all/orgs/default/projects/default_project/settings/services/DevSecOps_Frontend
    # TechDocs plugin
    backstage.io/techdocs-ref: dir:.
    # Jira plugin
    #jira/project-key: XYZ
