apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: boutique-frontend
  description: The frontend service of the Online Boutique application.
  links:
    - url: http://34.139.102.202/
      title: Online Boutique Website
      icon: dashboard
  tags:
    - microservices
    - frontend
    - TypeScript
    - boutique
  annotations:
    github.com/project-slug: GoogleCloudPlatform/microservices-demo
spec:
  type: service
  lifecycle: production
  owner: team-frontend
  system: online-boutique
  dependsOn:
    - component: boutique-cart
    - component: boutique-product-catalog
    - component: boutique-recommendation
    - component: boutique-shipping
    - component: boutique-payment
  providesApis:
    - boutique-frontend
