apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: boutique-product-catalog
  description: The Product Catalog Service manages the details of products available in the Online Boutique application.
  tags:
    - service
    - product-catalog
    - Python
    - boutique
  annotations:
    github.com/project-slug: GoogleCloudPlatform/microservices-demo
spec:
  type: service
  lifecycle: production
  owner: team-product-catalog
  system: online-boutique
  dependsOn:
    - component: recommendation
  providesApis:
    - boutique-product-catalog
