apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: boutique-recommendation
  description: The recommendation service for suggesting products.
  tags:
    - microservices
    - recommendation
    - python
    - boutique
  annotations:
    github.com/project-slug: GoogleCloudPlatform/microservices-demo
    harness.io/project-url: https://app.harness.io/ng/account/{{ account_id }}/all/orgs/{{ org_id }}/projects/{{ project_id }}
    # For Harness CI/CD plugin
    harness.io/pipelines: |
      Build and Deploy: https://app.harness.io/ng/account/{{ account_id }}/all/orgs/{{ org_id }}/projects/{{ project_id }}/pipelines/Online_Boutique_Build_and_Deploy/pipeline-studio?storeType=INLINE
    # TechDocs plugin
    backstage.io/techdocs-ref: dir:../
    # Jira plugin
    #jira/project-key: XYZ
spec:
  type: service
  lifecycle: production
  owner: team-recommendation
  system: online-boutique
  dependsOn:
    - component:product-catalog
  providesApis:
    - boutique-recommendation-api
  consumesApis:
    - boutique-product-catalog-api
